name: nyaya_assist
description: "NyayaAssist - AI-powered Police Back-Office SaaS."
publish_to: 'none'
version: 0.1.0+1

environment:
  sdk: ">=3.10.7 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Firebase Core
  firebase_core: ^2.24.2

  # Firebase Auth
  firebase_auth: ^4.15.3

  # Cloud Firestore
  cloud_firestore: ^4.13.3

  # Google Sign In
  google_sign_in: ^6.1.6

  # Google ML Kit Text Recognition
  google_mlkit_text_recognition: ^0.11.0

  # Gemini API (Generative AI)
  google_generative_ai: ^0.2.0
  googleapis: ^16.0.0
  extension_google_sign_in_as_googleapis_auth: ^2.0.13

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
